version: "3"
services:
  jenkins:
    # image: jenkins/jenkins:lts
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: jenkins
    restart: on-failure
    privileged: true
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - 8080:8080
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins
    depends_on:
      - docker

  docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    ports:
      - 2376:2376
    volumes:
     - jenkins-docker-certs:/certs/client
    networks:
      - jenkins

volumes:
  jenkins-docker-certs:
  jenkins-data:

networks:
  jenkins: